# Generated by Django 4.2.6 on 2023-10-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Корзина'},
        ),
    ]
